In [4]:
import sys
sys.path.extend(['/home/rohit/PhD_Work/GM_my_version/Graph_matching'])
import tools.graph_visu as gv
import tools.graph_processing as gp
import slam.io as sio
import numpy as np
import networkx as nx

In [18]:
path_to_graphs = '../data/simu_graph/0/test/0/noise_1400,outliers_8/graphs'
gt = np.load('../data/simu_graph/0/test/0/noise_1400,outliers_8/ground_truth.npy')
file_template_mesh = '../data/template_mesh/lh.OASIS_testGrp_average_inflated.gii'
file_sphere_mesh = '../data/template_mesh/ico100_7.gii'
path_to_simu_graphs = "/home/rohit/PhD_Work/GM_my_version/final_new_simu/0/noise_200,outliers_6/graphs"

In [6]:
list_graphs = gp.load_graphs_in_list(path_to_graphs)

In [19]:
list_graphs_final_simu = gp.load_graphs_in_list(path_to_simu_graphs)

In [8]:
gt_01 = gt[0][4]

g = list_graphs[0]
g1 = list_graphs[4]

dict_lab = {}
for node in g1.nodes:
    if node >=20:
        dict_lab[node] = {'label':-1}
    else:
        dict_lab[gt_01[node]] = {'label':node}

nx.set_node_attributes(g1,dict_lab)

dict_lab = {}
for node in g.nodes:
    if node >=20:
        dict_lab[node] = {'label':-1}
    else:
        dict_lab[node] = {'label':node}
nx.set_node_attributes(g,dict_lab)

In [30]:
g1.nodes

NodeView((0, 1, 27, 3, 4, 5, 6, 7, 22, 24, 10, 25, 12, 13, 14, 21, 26, 20, 18, 19, 17, 15, 8, 23, 9, 11, 16, 2))

In [31]:
gt_01

array([17, 10,  2,  0,  7,  1, 16,  9, 15,  3,  6, 11, 12,  8,  4, 18, 14,
       13,  5, 19])

In [33]:
for ind in gt_01:
    print(g.nodes.data()[ind])

{'coord': array([ 45.10137757, -88.06192035, -14.52459727]), 'label': 17}
{'coord': array([-50.03733913, -84.16323567, -20.31783587]), 'label': 10}
{'coord': array([-25.06130415,  95.60418922,  15.2239955 ]), 'label': 2}
{'coord': array([ -8.29375734, -99.58600481,   3.72038116]), 'label': 0}
{'coord': array([-70.04157873,  70.43770444,  11.51985424]), 'label': 7}
{'coord': array([-11.96701424,  65.4787652 ,  74.62788941]), 'label': 1}
{'coord': array([ 53.89179539,  82.41435684, -17.42263402]), 'label': 16}
{'coord': array([ 16.29928024, -35.40847182,  92.09002979]), 'label': 9}
{'coord': array([72.54483145, 11.61456095, 67.84061766]), 'label': 15}
{'coord': array([-36.95462701, -52.8159162 ,  76.45151757]), 'label': 3}
{'coord': array([-30.4412485 , -26.82708365, -91.39823835]), 'label': 6}
{'coord': array([-83.34326539,  -7.02261683, -54.81407635]), 'label': 11}
{'coord': array([-93.32844935,  35.80057941,  -2.84939583]), 'label': 12}
{'coord': array([ 71.22425583, -70.1867875 ,   0

In [9]:
for ind in gt_01:
    print(g1.nodes.data()[ind])

{'coord': array([ -7.08921669, -99.69244653,   3.34052568]), 'label': 0}
{'coord': array([-14.43493792,  65.07713683,  74.54259741]), 'label': 1}
{'coord': array([-24.44244742,  95.83289148,  14.78592829]), 'label': 2}
{'coord': array([-39.19324405, -55.35818349,  73.48034528]), 'label': 3}
{'coord': array([42.39562314, 86.65848551, 26.32333618]), 'label': 4}
{'coord': array([ 26.17043732, -94.89362398,  17.61557091]), 'label': 5}
{'coord': array([-28.03147283, -24.44624697, -92.82573749]), 'label': 6}
{'coord': array([-70.64631338,  70.32677352,   7.95256764]), 'label': 7}
{'coord': array([ 70.34214339, -70.46782012,   9.28812094]), 'label': 8}
{'coord': array([ 19.82312987, -37.47161023,  90.56998371]), 'label': 9}
{'coord': array([-51.58397888, -82.79133692, -22.01562294]), 'label': 10}
{'coord': array([-82.87257372,  -8.83594789, -55.26357345]), 'label': 11}
{'coord': array([-92.52863367,  37.06459574,  -8.04162256]), 'label': 12}
{'coord': array([ 72.07456722, -26.18460191,  64.18

In [10]:
sphere_mesh = sio.load_mesh(file_sphere_mesh)
mesh = gv.reg_mesh(sio.load_mesh(file_template_mesh))
gp.sphere_nearest_neighbor_interpolation(g, sphere_mesh)
gp.sphere_nearest_neighbor_interpolation(g1, sphere_mesh)

In [179]:
nodes_coords = gp.graph_nodes_to_coords(g, 'ico100_7_vertex_index', sphere_mesh)
nodes_coords_1 = gp.graph_nodes_to_coords(g1, 'ico100_7_vertex_index', sphere_mesh)

In [196]:
counter = 0
rest = []
for i in range(len(g.nodes)):
    for ind in gt_01:
        if(g.nodes.data()[i]['label'] == g1.nodes.data()[ind]['label']):
            print(g.nodes.data()[i]['coord'],g1.nodes.data()[ind]['coord'])
            counter+=1
        elif:
print(counter)

[ -8.29375734 -99.58600481   3.72038116] [ -7.08921669 -99.69244653   3.34052568]
[-11.96701424  65.4787652   74.62788941] [-14.43493792  65.07713683  74.54259741]
[-25.06130415  95.60418922  15.2239955 ] [-24.44244742  95.83289148  14.78592829]
[-36.95462701 -52.8159162   76.45151757] [-39.19324405 -55.35818349  73.48034528]
[42.60480034 87.95995566 21.16310915] [42.39562314 86.65848551 26.32333618]
[ 24.36019656 -95.13667031  18.85722104] [ 26.17043732 -94.89362398  17.61557091]
[-30.4412485  -26.82708365 -91.39823835] [-28.03147283 -24.44624697 -92.82573749]
[-70.04157873  70.43770444  11.51985424] [-70.64631338  70.32677352   7.95256764]
[ 71.22425583 -70.1867875    0.95929233] [ 70.34214339 -70.46782012   9.28812094]
[ 16.29928024 -35.40847182  92.09002979] [ 19.82312987 -37.47161023  90.56998371]
[-50.03733913 -84.16323567 -20.31783587] [-51.58397888 -82.79133692 -22.01562294]
[-83.34326539  -7.02261683 -54.81407635] [-82.87257372  -8.83594789 -55.26357345]
[-93.32844935  35.8005

In [15]:
un = nx.disjoint_union(g,g1)

In [40]:
for i in un.nodes():
    if((un.nodes.data()[i]['label']==50)):
       print(un.nodes.data()[i]['coord'])

[-56.11889642  25.04223002 -78.88951883]
[  2.77552172  97.88816609 -20.25347916]
[90.66891087 41.1681157  -9.18340084]
[-59.3130305   62.22627475  51.08674138]
[-16.49106543 -91.55535387  36.68326511]
[ 33.0934391  -78.95991037 -51.67356038]
[99.23325098 -8.58575806  8.89081878]
[62.88857825 58.68303726 51.00321424]
[ 76.43996182 -59.14811233 -25.65995021]
[-41.37398695 -14.95721347  89.80242184]
[-56.01050275 -81.91700632  12.34615961]
[  2.33495907 -88.65652333  46.20139432]
[ 34.32323732 -81.26778022 -47.0899488 ]
[ 24.10658203  22.49024288 -94.40901269]
[-30.7927306   65.37255605  69.12479047]
[ 50.5466927   38.5684428  -77.18488892]
